trainingInput:
    scaleTier: CUSTOM
    # Configure a master worker with no GPUs
    masterType: n1-standard-4
    # Configure 8 workers, each with no GPUs
    workerCount: 8
    workerType: n1-standard-4
    # Configure 5 parameter servers with no GPUs
    parameterServerCount: 5
    parameterServerType: n1-highmem-8
