trainingInput:
  scaleTier: CUSTOM
  # Configure a master worker with no GPUs
  masterType: n1-standard-4
  # Configure 2 workers, each with no GPUs
  workerCount: 2
  workerType: n1-standard-4
  # Configure 1 parameter server with no GPUs
  parameterServerCount: 1
  parameterServerType: n1-highmem-8
