trainingInput:
  scaleTier: CUSTOM
  # Configure a master worker with 1 K80 GPUs
  masterType: n1-standard-4
  masterConfig:
    acceleratorConfig:
      count: 1
      type: NVIDIA_TESLA_K80
  # Configure 4 workers, each with 1 K80 GPUs
  workerCount: 4
  workerType: n1-standard-4
  workerConfig:
    acceleratorConfig:
      count: 1
      type: NVIDIA_TESLA_K80
  # Configure 3 parameter servers with no GPUs
  parameterServerCount: 3
  parameterServerType: n1-highmem-8
